apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - secretbox:
        keys:
        - name: key1
          secret: AJznusgrZXDLbRfzaylU5QHuLn5mioxlrIWK7h52PTs=
    - identity: {}
