apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8n-test-app
  namespace: k8n-ns
  labels: 
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: k8n-test-app
          image: k8n-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          





      