apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: k8s-test-app
  namespace: k8s-dev
  labels:
    app: k8s-test-app
    version: v1 
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: k8s-test-app 
  template: 
    metadata:
      name: k8s-test-app
      labels:
        app: k8s-test-app
    spec:
      containers: 
        - name: k8s-test-app 
          image: k8s-test:v1
          # use 'minikube docker-env | Invoke-Expression'
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env: # apparently helps with displaying print statements in logs
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - configMapRef:
                name: fastapi-config
            # - secretRef:
            #     name: fastapi-secret
          volumeMounts:
            - name: fastapi-secret-vol
              mountPath: /etc/secrets
              readOnly: true
          resources: 
            requests: 
              cpu: "128m"
              memory: "128Mi" 
            limits:
              cpu: "256m"
              memory: "256Mi"
      volumes:
        - name: fastapi-secret-vol
          secret:
            secretName: fastapi-secret