apiVersion: v1 
kind: Secret 
metadata:
  name: fastapi-secret
  namespace: k8s-dev
stringData:
  POSTGRES_PASSWORD: secret1
  API_KEY: api_key_secret_1234
  POSTGRES_URL: postgresql+asyncpg://testusr:secret1@postgres-svc:5432/testdb