apiVersion: v1 
kind: Service 
metadata:
  name: postgres-svc
  labels: 
    app: postgres-svc 
  namespace: k8s-dev
spec:
  type: ClusterIP 
  selector: 
    app: postgres-db-app
  ports: 
    - port: 5432
      targetPort: 5432